### ISSUE TITLE
[Feature] Nicer error message for "Failed to fetch" 

### ISSUE THREAD

**Issue by jcace** [application-research/delta-ui#30]
If the UI is unable to reach DDM backend (ex, if DDM is not running) it currently just shows this error as shown below. Would be nicer if this error message was more descriptive - maybe something like 

> Could not connect to Delta-DM backend at http://url:port . Please ensure it is running and reachable on the network.

<img width="864" alt="Screenshot 2023-04-03 at 5 00 27 PM" src="https://user-images.githubusercontent.com/12418265/229652400-3679f4a6-3de8-46d1-ad13-cf695da497bd.png">

**Comment by jcace** [comment]
I think this is resolved, @elijaharita ?

**Comment by elijaharita** [comment]
Finally fixed this
