### ISSUE TITLE
[Feature] URL should have the route to the page

### ISSUE THREAD

**Issue by jcace** [application-research/delta-ui#4]
right now everything is at localhost:3005, but it should map to the specific page being viewed i.e,

`localhost:3005/datasets` for the datasets page and 
`localhost:3005/wallets` for the wallets page. 

This way the user can refresh and/or copy paste links and have it go to the right place

**Comment by elijaharita** [comment]
@jimmylee can you advise on how i should approach this?

**Comment by jimmylee** [comment]
Lets worry about this later, there is a smart way to do it but it requires a re-architecture
