### ISSUE TITLE
[Feature] Pagination UI - condensed

### ISSUE THREAD

**Issue by jcace** [application-research/delta-ui#52]
Rework the pagination so it behaves more like Boost - easier to manage for large numbers. 

<img width="484" alt="Screenshot 2023-05-25 at 11 16 13 AM" src="https://github.com/application-research/delta-ui/assets/12418265/18809e7b-e44e-4a90-a07c-18379c781eeb">

**Comment by LucRoy** [comment]
PR @ https://github.com/application-research/delta-ui/pull/60
