### ISSUE TITLE
[Feature] Show timestamps in local timezone

### ISSUE THREAD

**Issue by jcace** [application-research/delta-ui#57]
<img width="288" alt="Screenshot 2023-05-26 at 1 06 52 PM" src="https://github.com/application-research/delta-ui/assets/12418265/f46d4b25-3016-4491-ab7b-1a9236cbad4f">

Add an option to display time in the local timezone instead of GMT

Perhaps this could be a global setting for all timestamps in Delta UI

**Comment by LucRoy** [comment]
PR @ https://github.com/application-research/delta-ui/pull/71
